//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca_app
{


    public partial class Autor_Form
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control txtNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// Control rfvNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        /// <summary>
        /// Control txtApellido.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>
        /// Control rfvApellido.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApellido;

        /// <summary>
        /// Control txtNacionalidad.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNacionalidad;

        /// <summary>
        /// Control txtFechaNacimiento.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimiento;

        /// <summary>
        /// Control btnGuardar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// Control gvAutores.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAutores;
    }
}
