//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca_app
{


    public partial class Prestamo_Form
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control ddlUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlUsuario;

        /// <summary>
        /// Control rfvUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsuario;

        /// <summary>
        /// Control ddlEjemplar.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEjemplar;

        /// <summary>
        /// Control rfvEjemplar.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEjemplar;

        /// <summary>
        /// Control txtFechaLimite.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaLimite;

        /// <summary>
        /// Control rfvFechaLimite.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFechaLimite;

        /// <summary>
        /// Control txtObservaciones.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>
        /// Control btnGuardar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// Control gvPrestamos.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvPrestamos;
    }
}
